// Literals
ident = ? {XID_Start}{XID_Continue}* ?
number = ? 0-9* ?
string = '"' ? .* ? '"'
comment = ? #!.*\n ?

rhythm = '!' | '.'
expression = ident | number | rhythm

// Definition
expression = expression '=>' ident

// Concatenation
expression = expression ',' expression

// Expression
expression = '(' expression ')'

// Functions
type = ':' ( 'number' | 'string' | 'rhythm' | 'melody' | 'sequence' | 'pattern' )
expression = '\' ident '->' type expr '->' type
expression = expression '(' expression ')'  // Function call

// Scalars
expression =
	( '+' | '-' ) expression |
	expression ( '+' | '-' | '*' | '/' | 'lcm' | 'gcd' | '?' ) expression |
	expression ':' expression |

// Rhythm
expression =
	( '~' | "'" ) expression |
	expression ( '<' | '>' | '**' | 'or' | 'and' | 'xor' ) expression |
	expression '@' expression |   // Mapping

// Melody
expression =
	( '&' | "'" ) expression |
	expression '@' expression |   // Mapping
	expression ( '<' | '>' | '**' | '+' | '-' | '*' | '/' ) expression |

// Sequence
expression =
	expression ( '*' | '/' ) expression |
	expression '~>' string |

// Pattern
expression =
	'[' [( ',' expression )* [ ',' ]] ']' |  // Layer sequences
	expression '~>' string

// Program
program = [ expression [ (';' expression)* [ ';' ] ]]
